services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: bd_laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: